In [1]:
import pandas as pd

In [2]:
import sys
PACKAGE_FOLDER = "/Users/danielfiuzadosil/Documents/GitHub/raptor_functions/raptor_functions"
PACKAGE_FOLDER = "/Users/amash/Insync/GDrive/Projects/Raptor/raptor_functions"
sys.path.insert(0, PACKAGE_FOLDER)

In [4]:
path_to_measurements = 'data'

In [ ]:
from raptor_functions.supervised.preprocess import preprocess_all_files
df = preprocess_all_files(path_to_measurements, has_label= False)

In [4]:
df.to_csv('data/data.csv')

In [5]:
df.columns

Index(['timesteps', 'sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5',
       'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10',
       'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15',
       'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20',
       'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24', ' Humidity (r.h.)',
       'exp_unique_id', 'measurement_stage', 'date_exp', 'time_elapsed',
       'datetime_exp_start', 'filename', 'exp_name', 'repeat_no'],
      dtype='object')

In [8]:
df = pd.read_csv('/Users/amash/Insync/GDrive/Projects/Raptor/raptor_functions/raptor_functions/examples/daniel_examples/pigs_data/data.csv', index_col=0)

In [9]:
df

,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,...,sensor_24,Humidity (r.h.),exp_unique_id,measurement_stage,date_exp,time_elapsed,datetime_exp_start,filename,exp_name,repeat_no
0,1,476.250,397.227,492.131,479.955,497.618,195.377,340.400,396.126,110.550,...,480.701,47.24,0,baseline,1/8/2022,0.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1
1,2,474.049,395.030,491.355,477.726,496.040,194.976,339.531,395.030,110.340,...,473.319,47.18,0,baseline,1/8/2022,0.25,13:50:25,Test_1_20220801_13_50.txt,Test 24,1
2,3,474.781,395.030,491.355,476.987,496.040,194.976,339.531,394.484,110.340,...,471.864,47.18,0,baseline,1/8/2022,0.50,13:50:25,Test_1_20220801_13_50.txt,Test 24,1
3,4,474.781,395.030,492.131,477.726,496.828,194.776,339.531,394.484,110.131,...,472.591,47.18,0,baseline,1/8/2022,0.75,13:50:25,Test_1_20220801_13_50.txt,Test 24,1
4,5,475.514,393.939,492.909,476.250,496.828,194.776,339.531,393.939,110.131,...,471.864,47.11,0,baseline,1/8/2022,1.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,180,473.319,401.678,492.131,473.319,496.040,198.824,341.709,399.442,111.498,...,470.417,50.27,14,wait,1/8/2022,44.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1
180,181,471.864,400.558,491.355,474.049,496.828,198.414,341.272,399.442,111.498,...,470.417,50.27,14,wait,1/8/2022,45.00,13:38:39,Test_1_20220801_13_38.txt,Test 24,1
181,182,472.591,400.558,492.131,474.781,497.618,198.414,341.272,400.000,111.604,...,471.140,50.27,14,wait,1/8/2022,45.25,13:38:39,Test_1_20220801_13_38.txt,Test 24,1
182,183,473.319,401.678,492.131,473.319,496.040,198.414,340.400,400.000,111.604,...,471.864,50.27,14,wait,1/8/2022,45.50,13:38:39,Test_1_20220801_13_38.txt,Test 24,1
183,184,473.319,401.117,491.355,474.781,496.040,198.414,340.836,400.000,111.392,...,471.140,50.27,14,wait,1/8/2022,45.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1

In [10]:
FEATURES = ['sensor_1', 'sensor_2', 'sensor_3', 'sensor_4', 'sensor_5',
       'sensor_6', 'sensor_7', 'sensor_8', 'sensor_9', 'sensor_10',
       'sensor_11', 'sensor_12', 'sensor_13', 'sensor_14', 'sensor_15',
       'sensor_16', 'sensor_17', 'sensor_18', 'sensor_19', 'sensor_20',
       'sensor_21', 'sensor_22', 'sensor_23', 'sensor_24']

In [11]:
results = ['pig','pig',
'non-pig', 'non-pig',
'pig','pig',
'pig','pig',
'pig','pig',
'pig','pig',
'non-pig','non-pig',
'non-pig','non-pig']

In [12]:
lst = []
for i, group in enumerate(df.groupby('exp_unique_id')):
    group[1]['result'] = results[i]
    lst.append(group[1])
df = pd.concat(lst)

In [13]:
df

,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,sensor_9,...,Humidity (r.h.),exp_unique_id,measurement_stage,date_exp,time_elapsed,datetime_exp_start,filename,exp_name,repeat_no,result
0,1,476.250,397.227,492.131,479.955,497.618,195.377,340.400,396.126,110.550,...,47.24,0,baseline,1/8/2022,0.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
1,2,474.049,395.030,491.355,477.726,496.040,194.976,339.531,395.030,110.340,...,47.18,0,baseline,1/8/2022,0.25,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
2,3,474.781,395.030,491.355,476.987,496.040,194.976,339.531,394.484,110.340,...,47.18,0,baseline,1/8/2022,0.50,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
3,4,474.781,395.030,492.131,477.726,496.828,194.776,339.531,394.484,110.131,...,47.18,0,baseline,1/8/2022,0.75,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
4,5,475.514,393.939,492.909,476.250,496.828,194.776,339.531,393.939,110.131,...,47.11,0,baseline,1/8/2022,1.00,13:50:25,Test_1_20220801_13_50.txt,Test 24,1,pig
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
179,180,473.319,401.678,492.131,473.319,496.040,198.824,341.709,399.442,111.498,...,50.27,14,wait,1/8/2022,44.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
180,181,471.864,400.558,491.355,474.049,496.828,198.414,341.272,399.442,111.498,...,50.27,14,wait,1/8/2022,45.00,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
181,182,472.591,400.558,492.131,474.781,497.618,198.414,341.272,400.000,111.604,...,50.27,14,wait,1/8/2022,45.25,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
182,183,473.319,401.678,492.131,473.319,496.040,198.414,340.400,400.000,111.604,...,50.27,14,wait,1/8/2022,45.50,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig
183,184,473.319,401.117,491.355,474.781,496.040,198.414,340.836,400.000,111.392,...,50.27,14,wait,1/8/2022,45.75,13:38:39,Test_1_20220801_13_38.txt,Test 24,1,non-pig

In [ ]:
from raptor_functions.supervised.feature_extraction import get_training_features
df_f = get_training_features(df,features=FEATURES)

In [16]:
df_f

,"sensor_13__fft_coefficient__attr_""real""__coeff_8","sensor_13__fft_coefficient__attr_""real""__coeff_27","sensor_13__fft_coefficient__attr_""real""__coeff_56","sensor_15__fft_coefficient__attr_""real""__coeff_66",result
0,-6.547634,8.042483,-0.991310,-5.111312,pig
1,-2.503253,0.945323,2.908638,2.175913,pig
2,9.697768,9.915486,1.291418,6.488958,non-pig
3,11.083813,1.133818,3.379959,11.838423,non-pig
4,0.052211,5.247971,-0.153550,-6.763267,pig
5,-4.504075,-7.489260,0.415874,-8.241763,pig
6,-1.255184,-0.972125,-3.256959,-13.821351,pig
7,-1.518205,-2.372520,-1.427381,2.253852,pig
8,-4.241193,-1.221305,-3.117859,-15.014662,pig
9,11.852708,-4.500823,-10.613108,3.179063,pig
10,1.390613,0.136608,-3.576248,-10.901265,pig
11,1.165718,-0.142439,-2.418164,-7.919732,pig
12,8.603381,4.005279,4.220341,19.409199,non-pig
13,6.324421,2.833405,4.848984,19.097433,non-pig
14,3.099323,11.523196,2.101689,10.255836,non-pig

In [22]:
df_f.to_csv('df_f.csv')

In [1]:
import pandas as pd
import sys
PACKAGE_FOLDER = "/Users/danielfiuzadosil/Documents/GitHub/raptor_functions/raptor_functions"
PACKAGE_FOLDER = "/Users/amash/Insync/GDrive/Projects/Raptor/raptor_functions"
sys.path.insert(0, PACKAGE_FOLDER)

In [5]:
df_f = pd.read_csv('df_f.csv', index_col=0)
df_f

,"sensor_13__fft_coefficient__attr_""real""__coeff_8","sensor_13__fft_coefficient__attr_""real""__coeff_27","sensor_13__fft_coefficient__attr_""real""__coeff_56","sensor_15__fft_coefficient__attr_""real""__coeff_66",result
0,-6.547634,8.042483,-0.991310,-5.111312,pig
1,-2.503253,0.945323,2.908638,2.175913,pig
2,9.697768,9.915486,1.291418,6.488958,non-pig
3,11.083813,1.133818,3.379959,11.838423,non-pig
4,0.052211,5.247971,-0.153550,-6.763267,pig
5,-4.504075,-7.489260,0.415874,-8.241763,pig
6,-1.255184,-0.972125,-3.256959,-13.821351,pig
7,-1.518205,-2.372520,-1.427381,2.253852,pig
8,-4.241193,-1.221305,-3.117859,-15.014662,pig
9,11.852708,-4.500823,-10.613108,3.179063,pig
10,1.390613,0.136608,-3.576248,-10.901265,pig
11,1.165718,-0.142439,-2.418164,-7.919732,pig
12,8.603381,4.005279,4.220341,19.409199,non-pig
13,6.324421,2.833405,4.848984,19.097433,non-pig
14,3.099323,11.523196,2.101689,10.255836,non-pig

In [6]:
import mlflow
from raptor_functions.supervised.train import train_experiments
mlflow.end_run()
train_experiments(df_f, n_trials=5, study_name='pig-exp')

WARNING: Parameter shap='guess', but failed to guess the type of shap explainer to use for GaussianProcessClassifier. Defaulting to the model agnostic shap.KernelExplainer (shap='kernel'). However this will be slow, so if your model is compatible with e.g. shap.TreeExplainer or shap.LinearExplainer then pass shap='tree' or shap='linear'!
WARNING: For shap='kernel', shap interaction values can unfortunately not be calculated!
Note: shap values for shap='kernel' normally get calculated against X_background, but paramater X_background=None, so setting X_background=shap.sample(X, 50)...
Generating self.shap_explainer = shap.KernelExplainer(model, X, link='identity')
Building ExplainerDashboard..
Detected notebook environment, consider setting mode='external', mode='inline' or mode='jupyterlab' to keep the notebook interactive while the dashboard is running...
The explainer object has no decision_trees property. so setting decision_trees=False...
Generating layout...
Calculating shap values...

  0%|          | 0/5 [00:00<?, ?it/s]

Calculating prediction probabilities...
Calculating metrics...
Calculating confusion matrices...
Calculating classification_dfs...
Calculating roc auc curves...
Calculating pr auc curves...
Calculating liftcurve_dfs...
Calculating dependencies...
Calculating permutation importances (if slow, try setting n_jobs parameter)...
Calculating predictions...
Calculating pred_percentiles...
Reminder: you can store the explainer (including calculated dependencies) with explainer.dump('explainer.joblib') and reload with e.g. ClassifierExplainer.from_file('explainer.joblib')
Registering callbacks...

[W 2022-08-18 17:18:33,913] Trial 4 failed, because the value None could not be cast to float.

Click on this link to track experiments:  http://ec2-18-133-140-90.eu-west-2.compute.amazonaws.com:5000/