#### Install raptor-functions

In [1]:
!pip install raptor-functions -q

### Model Prediction

In [1]:
from raptor_functions.supervised.prediction import make_ensemble_prediction
from raptor_functions.supervised.preprocess import preprocess_single_file

In [2]:
f = 'test.txt'

In [3]:
df_sample = preprocess_single_file(f)

/Users/amash/anaconda3/envs/demodemo/lib/python3.8/site-packages/raptor_functions/supervised/preprocess.py:130: UserWarning: Warning...........Can't get label
  warnings.warn("Warning...........Can't get label")

In [4]:
df_sample

,exp_unique_id,timesteps,sensor_1,sensor_2,sensor_3,sensor_4,sensor_5,sensor_6,sensor_7,sensor_8,...,sensor_24,humidity,measurement_stage,date_exp,time_elapsed,datetime_exp_start,filename,exp_name,repeat_no,result
0,0,0.0,316.809,315.735,315.687,313.562,311.748,315.806,316.308,316.236,...,103.452,28.283,baseline,20/01/2022,0.00,15:27:35,test.txt,18a,2,Other
1,0,1.0,316.427,315.902,316.069,313.729,311.939,315.950,316.260,315.806,...,103.452,35.682,baseline,20/01/2022,0.25,15:27:35,test.txt,18a,2,Other
2,0,2.0,316.117,316.403,316.188,313.586,311.461,315.878,315.926,315.782,...,103.619,45.789,baseline,20/01/2022,0.50,15:27:35,test.txt,18a,2,Other
3,0,3.0,316.141,315.639,316.093,313.491,311.103,315.496,316.164,315.735,...,103.404,52.377,baseline,20/01/2022,0.75,15:27:35,test.txt,18a,2,Other
4,0,4.0,316.857,315.878,315.878,313.419,311.557,315.806,316.451,315.902,...,103.357,52.557,baseline,20/01/2022,1.00,15:27:35,test.txt,18a,2,Other
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
148,0,148.0,315.806,316.236,316.093,313.753,311.724,315.950,315.926,315.663,...,103.667,40.510,flush,20/01/2022,37.00,15:27:35,test.txt,18a,2,Other
149,0,149.0,316.618,315.806,315.806,313.682,312.130,315.782,316.546,316.117,...,103.619,31.125,flush,20/01/2022,37.25,15:27:35,test.txt,18a,2,Other
150,0,150.0,316.164,315.926,316.069,313.562,312.034,316.141,316.021,316.164,...,103.476,26.704,flush,20/01/2022,37.50,15:27:35,test.txt,18a,2,Other
151,0,151.0,316.499,316.093,315.830,313.324,311.891,316.093,316.332,315.997,...,103.548,28.869,flush,20/01/2022,37.75,15:27:35,test.txt,18a,2,Other
152,0,152.0,316.427,315.878,315.854,313.801,311.724,315.926,315.902,315.806,...,103.667,36.359,flush,20/01/2022,38.00,15:27:35,test.txt,18a,2,Other

In [ ]:
final_pred, preds = make_ensemble_prediction(df_sample)